package dev.unicompose

import dev.unicompose.style.Color
import dev.unicompose.style.Dp
import dev.unicompose.style.argb

/**
 * Default divider color — 12% opaque black. Lives in its own file because
 * top-level vals collocated with `expect fun UiDivider` collide with the JVM
 * class generated by the actual function in `composeAppMain`.
 */
public val DefaultDividerColor: Color = argb(31, 0, 0, 0)

/** Default divider thickness — 1dp. */
public val DefaultDividerThickness: Dp = Dp(1f)
