package dev.unicompose

import dev.unicompose.style.FontWeight
import dev.unicompose.style.Style
import dev.unicompose.style.sp

/**
 * Default visual style per heading level. Public for advanced use.
 *
 * Lives in its own file because a top-level function collocated with
 * `expect fun UiHeading` collides with the JVM class generated by the actual
 * function in `composeAppMain`.
 */
public fun defaultHeadingStyle(level: HeadingLevel): Style = when (level) {
    HeadingLevel.H1 -> Style(fontSize = 28.sp, fontWeight = FontWeight.Bold)
    HeadingLevel.H2 -> Style(fontSize = 22.sp, fontWeight = FontWeight.Bold)
    HeadingLevel.H3 -> Style(fontSize = 18.sp, fontWeight = FontWeight.SemiBold)
}
